<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "asyahoofinance"
 *
 * Auto generated by Extension Builder 2015-10-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
    'title' => 'AS Yahoo Finance',
    'description' => 'The Extension provides a plugin to show financial statistics from a YahooFinance channel.',
    'category' => 'plugin',
    'author' => 'Golovasty Artur - ALPEIN Software Ltd. & Co. KG',
    'author_email' => 'artur.golovasty@alpeinsoft.ch',
    'author_company' => 'ALPEIN Software Ltd. & Co. KG',
    'state' => 'stable',
    'uploadfolder' => false,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.2',
    'constraints' =>
        array(
        'depends' =>
            array(
            'typo3' => '6.2.0-8.3.99',
        ),
        'conflicts' =>
            array(
        ),
        'suggests' =>
            array(
        ),
    ),
    'clearcacheonload' => false,
);
